---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "siriapp"
  namespace: "default"
  labels:
    app: "siriapp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "siriapp"
  template:
    metadata:
      labels:
        app: "siriapp"
    spec:
      containers:
      - name: "onlinevegetablesale-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/sirishabb/onlinevegetablesale@sha256:1c6effd338d497fcbf51d3cdb4e856feb991a5a4784bb02aba2594f3fa08d307"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "siriapp-hpa-cpdu"
  namespace: "default"
  labels:
    app: "siriapp"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "siriapp"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
