---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "sirishaapp"
  namespace: "default"
  labels:
    app: "sirishaapp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "sirishaapp"
  template:
    metadata:
      labels:
        app: "sirishaapp"
    spec:
      containers:
      - name: "onlinevegetablesale-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/sirishabb/onlinevegetablesale@sha256:c2f4712e00c514e2167d2198092ddd25089d539edcd0de66ca5f9bf9740ebc34"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "sirishaapp-hpa-gpqe"
  namespace: "default"
  labels:
    app: "sirishaapp"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "sirishaapp"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
